---

- name: Create AAEP
  cisco.aci.aci_rest:
    host: "{{ aci_host }}"
    username: "{{ aci_user_name }}"
    password: "{{ ansible_password }}"
    validate_certs: no
    use_ssl: yes
    output_level: info
    method: post
    path: /api/node/mo/uni.json
    content: "{{ lookup('template', 'j2/aaep-template.yaml.j2') | from_yaml }}"
  register: domain_results
  delegate_to: localhost
  tags: always