---

- name: Tenant / VRF Creation Demo
  hosts: all
  connection: local
  gather_facts: no
  vars_files:
    - ./variables/tenant/tenant.yaml
    - ./variables/tenant/vrf.yaml

  tasks:
    
    - name: "Build a Tenant"
      include_tasks: ./tasks/tenant/001-build_a_tenant.yaml
      tags:
        - tenant
    
    - name: "Build VRFs"
      include_tasks: ./tasks/tenant/002-build_a_vrf.yaml
      loop: "{{ vrf }}"
      tags:
        - vrf

